spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test@example.com
spring.mail.password=dummy
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false